# ?? ?? ??
server:
  port: 9090

# ?????? ??
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/react_spring_blog
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect  #JPA? ??? database? dialect ??
    properties:
      hibernate:
        hibernate:
        "[format_sql]": true            #SQL? ?? ?? ??
        "[user_sql_comments]": true     #SQL?? ? ?? ??
        "[highlight_sql]": true         #SQL? ??
        "[hbm2ddl.auto]": create
    open-in-view: true
    show-sql: true