server:
  port: 8989

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/react_spring_blog
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        hibernate:
        "[format_sql]": true            #SQL ??
        "[user_sql_comments]": true     #SQL ?? ??
        "[highlight_sql]": true         #SQL ??
        "[hbm2ddl.auto]": update
    open-in-view: true
    show-sql: true

#jwt:
#  header: Authorization
#  prefix: Bearer
#  secret:
#  tokenExpirationTime: 18000          #?? ?? ?? (?: 300?)
